### ISSUE TITLE
404 error and incorrect re-direct links

### ISSUE THREAD

**Issue by laurenwigmore** [open-revolution/openrevolution#96]
Correct the 404 error and links that now incorrectly route to the Diginomics course, instead of the Open Revolution book page.

## Acceptance

- [x] All pages work **✅2023-12-28 i believe they do**
- [x] All links updated **✅2023-12-28 believe done - see below (this is underspecified)**

## Tasks

- [x] this page needs to be updated as it has a 404 error https://diginomics.io/book **✅2023-12-28 ❌ WONTFIX. the book link in navbar is obsolete as moved book back to home page in **
- [x] Review all Open Revolution or 'book' related links and re-route as needed back to the Open Revolution page **✅2023-12-28 ❌ have moved book page back to home**

Example: https://diginomics.io/make-it-happen
![image](https://github.com/life-itself/diginomics/assets/132304704/47e2a6bc-bbdf-4ad0-a558-0e6f4acf12c9)

**Comment by rufuspollock** [comment]
FIXED. Moved openrevolution book page back to home page.
